# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push
      run: |
        docker login --username ${{ secrets.GH_USERNAME }} --password-stdin ${{ secrets.GH_PAT }} ghcr.io
        docker built . -t ghcr.io/tommynunez/lemonadestandapi:latest
        docker push ghcr.io/tommynunez/lemonadestandapi:latest