name: Trigger auto deployment for lemonadestand

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ release ]
    paths:
    - '**'
    - '.github/workflows/lemonadestand-AutoDeployTrigger-112477e2-7b69-449d-96bf-5e0e00b86dd6.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: lemonadestand.azurecr.io
          username: ${{ secrets.LEMONADESTAND_REGISTRY_USERNAME }}
          password: ${{ secrets.LEMONADESTAND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lemonadestand.azurecr.io/lemonadestand:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LEMONADESTAND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n lemonadestand -g tonnect --server lemonadestand.azurecr.io --username  ${{ secrets.LEMONADESTAND_REGISTRY_USERNAME }} --password ${{ secrets.LEMONADESTAND_REGISTRY_PASSWORD }}
            az containerapp update -n lemonadestand -g tonnect --image lemonadestand.azurecr.io/lemonadestand:${{ github.sha }}
